DROP TABLE IF EXISTS "anime_resource_categories" CASCADE;
DROP TABLE IF EXISTS "anime_cast_credits" CASCADE;
DROP TABLE IF EXISTS "anime_staff_credits" CASCADE;
DROP TABLE IF EXISTS "episodes" CASCADE;
DROP TABLE IF EXISTS "broadcast_info" CASCADE;
DROP TABLE IF EXISTS "anime_seasons" CASCADE;
DROP TABLE IF EXISTS "seasons" CASCADE;
DROP TABLE IF EXISTS "anime" CASCADE;
DROP TYPE IF EXISTS "resource_category";
DROP TYPE IF EXISTS "episode_publication_status";
DROP TYPE IF EXISTS "episode_type";
DROP TYPE IF EXISTS "weekday";
DROP TYPE IF EXISTS "broadcast_state";
DROP TYPE IF EXISTS "broadcast_type";
DROP TYPE IF EXISTS "anime_season_relation_type";
DROP TYPE IF EXISTS "season_type";
DROP TYPE IF EXISTS "season_quarter";
DROP TYPE IF EXISTS "data_status";
DROP TYPE IF EXISTS "anime_release_status";
DROP TYPE IF EXISTS "anime_media_type";
